import './globals.css';
import { AuthSession } from 'components/common/auth/AuthSession';
import { jua } from 'utils/fonts';
import QueryProvider from '@components/common/query/QueryProvider';

export const metadata = {
  title: 'quokka letter',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <body className={`${jua.className}`}>
        <div id="modal" />
        <AuthSession>
          <QueryProvider>
            <main className="mx-auto max-w-[500px] h-screen">
              {children}
              <div className="absolute right-0 bottom-0 h-screen w-[calc(50%-250px)] bg-white" />
            </main>
          </QueryProvider>
        </AuthSession>
      </body>
    </html>
  );
}
