import './globals.css';
import { AuthSession } from 'components/common/auth/AuthSession';

export const metadata = {
  title: 'quokka letter',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <body>
        <AuthSession>
          <main className="mx-auto max-w-[400px]">{children}</main>
        </AuthSession>
      </body>
    </html>
  );
}
